services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB_NAME}'
    volumes:
      - copilot-db-volume:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - copilot-redis-volume:/data
volumes:
  copilot-db-volume:
  copilot-redis-volume: