services:
  db:
    image: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB_NAME}'
    volumes:
      - copilot-db-volume:/var/lib/postgresql/data
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: always
    command: --cluster_mode=emulated --lock_on_hashtags
    ulimits:
      memlock: -1
    ports:
      - "${DRAGONFLY_PORT}:6379"
    volumes:
      - copilot-dragonfly-volume:/data
volumes:
  copilot-db-volume:
  copilot-dragonfly-volume: